<header>
    <nav>
        <ul>
            <li>
                <a href="https://gaelfelix.sites.3wa.io/cours-3wa/php/bre02-php-j2/require/index.php?route=home">Accueil</a>
            </li>
            <li>
                <a href="https://gaelfelix.sites.3wa.io/cours-3wa/php/bre02-php-j2/require/index.php?route=about">À propos</a>
            </li>
            <li>
                <a href="https://gaelfelix.sites.3wa.io/cours-3wa/php/bre02-php-j2/require/index.php?route=contact">Contact</a>
            </li>
        </ul>
    </nav>
</header>