<?php
$routeHome = "home";
$routeAbout = "about";
$routeContact = "contact";
?>

<header>
    <nav>
        <ul>
            <li>
                <a href="https://gaelfelix.sites.3wa.io/cours-3wa/php/bre02-php-j2/require/index.php?route=<?= $routeHome ?>">Accueil</a>
            </li>
            <li>
                <a href="https://gaelfelix.sites.3wa.io/cours-3wa/php/bre02-php-j2/require/index.php?route=<?= $routeAbout ?>">À propos</a>
            </li>
            <li>
                <a href="https://gaelfelix.sites.3wa.io/cours-3wa/php/bre02-php-j2/require/index.php?route=<?= $routeContact ?>">Contact</a>
            </li>
        </ul>
    </nav>
</header>