<header>
    <nav>
        <ul>
            <li>
                <a <?php $route = "home" ?> href="https://gaelfelix.sites.3wa.io/cours-3wa/php/bre02-php-j2/require/index.php?route=<?= $route ?>">Accueil</a>
            </li>
            <li>
                <a <?php $route = "about" ?> href="https://gaelfelix.sites.3wa.io/cours-3wa/php/bre02-php-j2/require/index.php?route=<?= $route ?>">À propos</a>
            </li>
            <li>
                <a <?php $route = "contact" ?> href="https://gaelfelix.sites.3wa.io/cours-3wa/php/bre02-php-j2/require/index.php?route=<?= $route ?>">Contact</a>
            </li>
        </ul>
    </nav>
</header>